# Generated by Django 4.2 on 2025-10-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tieba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tieba.post', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
