# Generated by Django 4.2 on 2025-10-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0002_post_favorite_count_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='是否为草稿'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
    ]
